title: Protocol Primer
description: "Explaining technical changes in Bitcoin in simple, neutral language"
url: "https://talks2bots.github.io"
baseurl: "/protocolprimer"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site settings
locale: "en-US"
search: true
repository: "Talks2Bots/protocolprimer"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Includes & Excludes
include:
  - _pages
  - assets

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name: "Protocol Primer"
  bio: "Explaining technical changes in Bitcoin in simple, neutral language"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/protocolprimer"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true 